NFL_API_KEY: 'x69q65ye8dpps7f547nm5ahv'
NHL_API_KEY: '2597mst8gj5mvf722ua44hbs'
NBA_API_KEY: 'dxfd5yns7g99byupjfvw5nuw'
MLB_API_KEY: 'bnfs9aep4f9zsveptxtq7pqd'
NCAAFB_API_KEY: 'bayy2puucubhb9j99k5fsg2y4'
NCAAMB_API_KEY: '259zh22gznp2jwyhhnv8uvvg'
NASCAR_API_KEY: '4tgwqgamj4q8x4dr8f4fpzcq'
GOLF_API_KEY: 'canzbgq8nzyn8ecwp2mrwpnx'
API_MODE: 't'
