# Sportsdata Sport Data API Keys
SPORTSDATA_NFL_API_KEY:    ''
SPORTSDATA_NHL_API_KEY:    ''
SPORTSDATA_NBA_API_KEY:    ''
SPORTSDATA_MLB_API_KEY:    ''
SPORTSDATA_NCAAFB_API_KEY: ''
SPORTSDATA_NCAAMB_API_KEY: ''
SPORTSDATA_NASCAR_API_KEY: ''
SPORTSDATA_GOLF_API_KEY:   ''

# Sportsdata Sport Images API Keys
SPORTSDATA_NFL_API_KEY:    ''
SPORTSDATA_NHL_API_KEY:    ''
SPORTSDATA_NBA_API_KEY:    ''
SPORTSDATA_MLB_API_KEY:    ''
SPORTSDATA_NCAAFB_API_KEY: ''
SPORTSDATA_NCAAMB_API_KEY: ''
SPORTSDATA_NASCAR_API_KEY: ''
SPORTSDATA_GOLF_API_KEY:   ''

SPORTSDATA_API_MODE: 't'
